# Generated by Django 4.1.7 on 2023-03-27 18:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="deadline",
            field=models.DateField(
                blank=True, null=True, verbose_name="крайний срок сдачи"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="описание"),
        ),
        migrations.AlterField(
            model_name="task",
            name="name",
            field=models.CharField(max_length=35, verbose_name="заголовок"),
        ),
        migrations.AddConstraint(
            model_name="task",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("deadline__gt", datetime.datetime(2023, 3, 27, 18, 11, 7, 892203))
                ),
                name='deadline_constraint',
            ),
        ),
    ]
